require_relative 'config/environment'

use PermissionController
use SystemController
use RoleController
use UserController
use LoginController
use PermissionController
use UserController
run ApplicationController